name 'chef-compliance-demo'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-compliance-demo'
long_description 'Installs/Configures chef-compliance-demo'
version '0.1.0'
